name: Automatically check that all links work

on:
  push:
    branches:
      - main
  schedule:
    - cron:  "30 8 * * *"

jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - run: |
          python -m pip install --upgrade pip
          pip3 install requests
          pip3 install pyyaml
      - name: Check that links work
        run: |
          python3 .code/check_links.py
