name: Produce exported formats

on:
  push:
    branches:
      - main

jobs:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - run: |
      python -m pip install --upgrade pip
      pip3 install pandas
      pip3 install pyyaml
    - name: Run export script
      run: |
      python3 ./.build/export.py
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        path: dist/*
    - name: Publish on web
      uses: ad-m/github-push-action@v0.5.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
        force: true
        directory: dist/
